description: An easily-extensible web server framework in Dart.
homepage: https://github.com/angel-dart/angel
name: hn
publish_to: none
dependencies:
  angel_auth: ^1.0.0
  angel_configuration: ^1.0.0
  angel_cors: ^1.0.0
  angel_file_service: ^1.0.0
  angel_framework: ^1.1.0
  angel_jael: ^1.0.0
  angel_paginate: ^1.0.0
  angel_static: ^1.3.0
  angel_validate: ^1.0.0
  canonical_url: ^1.0.0
  dart2_tryparse: ^1.0.0
  pooled_map: ^1.0.0
  timeago: ^1.0.0
dev_dependencies: 
  angel_hot: ^1.0.0
  angel_serialize_generator: ^2.0.0
  build_runner: ^0.8.0
  console: ^2.2.4
